### ISSUE TITLE
Datalog plugin does not handle base type syntax correctly

### ISSUE THREAD

**Issue by markww** [LFrobeen/intellij-datalog#4]
Souffle Datalog has a pattern called a [base type](https://souffle-lang.github.io/types#base-type), which is structurally the same as a primitive type, but different base types will not implicitly cast to each other. Below is an example of the base type syntax:

```
.type Country <: symbol
```

The intellij datalog plugin appears to not recognize the <: symbol and highlights it with a red squiggly underline.

**Comment by LFrobeen** [comment]
Should be fixed in the next update. The update will be available in 2 days or so via the IDEs plugin manager. You can get it earlier by downloading and installing it directly from [the releases page.](https://github.com/LFrobeen/intellij-datalog/releases/tag/v2.0.0)
